#DEV  environment

# app.message=Este eh a propriedade do arquivo ${spring.application.name}
# app.ambiente=Desenvolvimento

# Usando application-dev.properties
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
# spring.datasource.username=usuario
# spring.datasource.password=senha

app: 
  message: Este eh a propriedade do arquivo ${spring.application.name}
  ambiente: Desenvolvimento

spring: 
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: usuario
    password: senha
  
# server:
#   port: 9092