#PROD  environment

# Usando o application-pro.properties
# 
# app.message=Este eh a propriedade do arquivo ${spring.application.name}
# app.ambiente=Producao
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=<MYSQL_URL>
# spring.datasource.username=<USERNAME>
# spring.datasource.password=<PASSWORD>

app:
  message: Este eh a propriedade do arquivo ${spring.application.name}
  ambiente: Producao

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <MYSQL_URL>
    username: <USERNAME>
    password: <PASSWORD>

# server:
#   port: 9091