/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package databaseconn;

import databaseconn.dao.ClientDAO;
import java.sql.Connection;


public class App {
	
    public static void main(String[] args) {

      ClientDAO client = new ClientDAO();
      ClientDAO.showTable(client.listAll());
      
    }
}
